FROM {{ image.base_image }}

LABEL maintainer="WarpPanel Team"
LABEL org.opencontainers.image.title="WarpPanel MariaDB {{ image.version }} (Alpine)"
LABEL org.opencontainers.image.description="Ultra-lightweight and tuned MariaDB server for WarpPanel hosting"

COPY custom.cnf /etc/my.cnf.d/99-warppanel.cnf
RUN chmod 644 /etc/my.cnf.d/99-warppanel.cnf

EXPOSE 3306

CMD ["mariadbd"]
